import os
import requests
from typing import Dict, Any, List, Optional

API = "https://api.github.com"


class GitHubRepoTool:
    """Creates GitHub repositories from generated artifacts.

    Uses the NEXUS_GITHUB_TOKEN environment variable (GitHub Actions secret).
    If the token is missing, every method returns a clear, honest message
    instead of failing silently.
    """

    @staticmethod
    def _token() -> Optional[str]:
        return os.getenv("NEXUS_GITHUB_TOKEN") or os.getenv("GITHUB_TOKEN")

    @staticmethod
    def available() -> bool:
        return bool(GitHubRepoTool._token())

    @staticmethod
    def _headers() -> Dict[str, str]:
        return {
            "Authorization": f"Bearer {GitHubRepoTool._token()}",
            "Accept": "application/vnd.github+json",
        }

    @classmethod
    def create_repo(cls, name: str, description: str = "", private: bool = False, files: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
        """Create a repository and seed it with files in a single commit.

        files: mapping of file path -> content. Returns a result dict with
        'status' ('created' | 'no_token' | 'error'), 'url', and 'message'.
        """
        token = cls._token()
        if not token:
            return {
                "status": "no_token",
                "url": None,
                "message": (
                    "[System] Repo creation requested but no GitHub token is configured. "
                    "Add the NEXUS_GITHUB_TOKEN repository secret (fine-grained, Contents "
                    "read/write + Administration read/write on your account) and rerun."
                ),
            }

        name = name.strip().lower().replace(" ", "-")
        if not name:
            return {"status": "error", "url": None, "message": "Invalid repository name."}

        try:
            res = requests.post(
                f"{API}/user/repos",
                headers=cls._headers(),
                json={"name": name, "description": description[:350], "private": private, "auto_init": False},
                timeout=30,
            )
            if res.status_code not in (200, 201):
                # Repo may already exist under the account
                owner = requests.get(f"{API}/user", headers=cls._headers(), timeout=30).json().get("login", "")
                existing = requests.get(f"{API}/repos/{owner}/{name}", headers=cls._headers(), timeout=30)
                if existing.status_code == 200:
                    repo = existing.json()
                else:
                    return {"status": "error", "url": None, "message": f"GitHub API {res.status_code}: {res.json().get('message', '')}"}
            else:
                repo = res.json()

            if files:
                cls._seed_files(repo["full_name"], files)

            return {
                "status": "created",
                "url": repo["html_url"],
                "message": f"[System] Repository created: {repo['html_url']} ({len(files or {})} files seeded).",
            }
        except Exception as e:
            return {"status": "error", "url": None, "message": f"[System] Repo creation failed: {e}"}

    @classmethod
    def _seed_files(cls, full_name: str, files: Dict[str, str]):
        """Push files via the git data API: blobs -> tree -> commit -> ref."""
        blobs = []
        for path, content in files.items():
            blob = requests.post(
                f"{API}/repos/{full_name}/git/blobs",
                headers=cls._headers(),
                json={"content": content, "encoding": "utf-8"},
                timeout=30,
            )
            blob.raise_for_status()
            blobs.append({"path": path, "mode": "100644", "type": "blob", "sha": blob.json()["sha"]})

        tree = requests.post(
            f"{API}/repos/{full_name}/git/trees",
            headers=cls._headers(),
            json={"tree": blobs},
            timeout=30,
        )
        tree.raise_for_status()

        commit = requests.post(
            f"{API}/repos/{full_name}/git/commits",
            headers=cls._headers(),
            json={
                "message": "initial: generated by Nexus autonomous agent",
                "tree": tree.json()["sha"],
            },
            timeout=30,
        )
        commit.raise_for_status()

        requests.post(
            f"{API}/repos/{full_name}/git/refs",
            headers=cls._headers(),
            json={"ref": "refs/heads/main", "sha": commit.json()["sha"]},
            timeout=30,
        ).raise_for_status()
